//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Emu48.rc
//
#define IDM_DEBUG_SETTINGS              0x0010
#define IDI_EMU48                       100
#define IDR_MENU                        101
#define IDM_MENU                        102
#define IDR_DEBUG                       103
#define IDR_DEBUG_TOOLBAR               104
#define IDR_DEBUG_CODE                  105
#define IDR_DEBUG_MEM                   106
#define IDR_DEBUG_STACK                 107
#define IDB_CHECKBOX                    108
#define IDD_ABOUT                       109
#define IDD_SET_GENERAL                 110
#define IDD_SET_MEMORY                  111
#define IDD_SET_PERIPHERAL              112
#define IDD_CHOOSEKML                   113
#define IDD_KMLLOG                      114
#define IDD_DISASM                      115
#define IDD_DEBUG                       116
#define IDD_NEWVALUE                    117
#define IDD_ENTERADR                    118
#define IDD_BREAKEDIT                   119
#define IDD_ENTERBREAK                  120
#define IDD_INSTRUCTIONS                121
#define IDD_WRITEONLYREG                122
#define IDD_FIND                        123
#define IDD_PROFILE                     124
#define IDD_RPLVIEW                     125
#define IDD_MACROSET                    126
#define IDD_DEBUG_MEMSAVE               127
#define IDD_DEBUG_MEMLOAD               128
#define IDD_DEBUG_SETTINGS              129
#define IDC_REALSPEED                   1000
#define IDC_GRAYSCALE                   1001
#define IDC_ALWAYSONTOP                 1002
#define IDC_ACTFOLLOWSMOUSE             1003
#define IDC_SINGLEINSTANCE              1004
#define IDC_AUTOSAVE                    1005
#define IDC_AUTOSAVEONEXIT              1006
#define IDC_OBJECTLOADWARNING           1007
#define IDC_SHOWTITLE                   1008
#define IDC_SHOWMENU                    1009
#define IDC_ALWAYSDISPLOG               1010
#define IDC_PORT1EN                     1011
#define IDC_PORT1WR                     1012
#define IDC_PORT2ISSHARED               1013
#define IDC_PORT2WR                     1014
#define IDC_PORT2                       1015
#define IDC_PORT2LOAD                   1016
#define IDC_IR_ADDR                     1017
#define IDC_IR_PORT                     1018
#define IDC_WIRE                        1019
#define IDC_IR                          1020
#define IDC_EMUDIR                      1021
#define IDC_EMUDIRSEL                   1022
#define IDC_UPDATE                      1023
#define IDC_KMLSCRIPT                   1024
#define IDC_AUTHOR                      1025
#define IDC_TITLE                       1026
#define IDC_KMLLOG                      1027
#define IDC_VERSION                     1028
#define IDC_LICENSE                     1029
#define IDC_DISASM_WIN                  1030
#define IDC_DISASM_MODE_TEXT            1031
#define IDC_DISASM_MODE                 1032
#define IDC_DISASM_MODULE               1033
#define IDC_DISASM_HP                   1034
#define IDC_DISASM_CLASS                1035
#define IDC_ADDRESS                     1036
#define IDC_DISASM_ADR                  1037
#define IDC_DISASM_NEXT                 1038
#define IDC_DISASM_COPY                 1039
#define IDC_DEBUG_CODE                  1040
#define IDC_STATIC_CODE                 1041
#define IDC_STATIC_REGISTERS            1042
#define IDC_STATIC_MEMORY               1043
#define IDC_STATIC_STACK                1044
#define IDC_REG_A                       1045
#define IDC_REG_B                       1046
#define IDC_REG_C                       1047
#define IDC_REG_D                       1048
#define IDC_REG_R0                      1049
#define IDC_REG_R1                      1050
#define IDC_REG_R2                      1051
#define IDC_REG_R3                      1052
#define IDC_REG_R4                      1053
#define IDC_REG_D0                      1054
#define IDC_REG_D1                      1055
#define IDC_REG_P                       1056
#define IDC_REG_PC                      1057
#define IDC_REG_OUT                     1058
#define IDC_REG_IN                      1059
#define IDC_REG_ST                      1060
#define IDC_REG_CY                      1061
#define IDC_REG_MODE                    1062
#define IDC_REG_MP                      1063
#define IDC_REG_SR                      1064
#define IDC_REG_SB                      1065
#define IDC_REG_XM                      1066
#define IDC_MISC_INT                    1067
#define IDC_MISC_KEY                    1068
#define IDC_MISC_BS                     1069
#define IDC_NEWVALUE                    1070
#define IDC_ENTERADR                    1071
#define IDC_DEBUG_MEM                   1072
#define IDC_DEBUG_MEM_ADDR              1073
#define IDC_DEBUG_MEM_COL0              1074
#define IDC_DEBUG_MEM_COL1              1075
#define IDC_DEBUG_MEM_COL2              1076
#define IDC_DEBUG_MEM_COL3              1077
#define IDC_DEBUG_MEM_COL4              1078
#define IDC_DEBUG_MEM_COL5              1079
#define IDC_DEBUG_MEM_COL6              1080
#define IDC_DEBUG_MEM_COL7              1081
#define IDC_DEBUG_MEM_TEXT              1082
#define IDC_DEBUG_DATA_FILE             1083
#define IDC_DEBUG_DATA_BUT              1084
#define IDC_DEBUG_DATA_STARTADDR        1085
#define IDC_DEBUG_DATA_ENDADDR          1086
#define IDC_DEBUG_SET_SYMB              1087
#define IDC_DEBUG_SET_MODEL             1088
#define IDC_DEBUG_SET_FILE              1089
#define IDC_DEBUG_SET_BROWSE            1090
#define IDC_DEBUG_STACK                 1091
#define IDC_STATIC_BREAKPOINT           1092
#define IDC_BREAKEDIT_ADD               1093
#define IDC_BREAKEDIT_DELETE            1094
#define IDC_BREAKEDIT_WND               1095
#define IDC_STATIC_MMU                  1096
#define IDC_MMU_IO_A                    1097
#define IDC_MMU_NCE2_A                  1098
#define IDC_MMU_CE1_A                   1099
#define IDC_MMU_CE2_A                   1100
#define IDC_MMU_NCE3_A                  1101
#define IDC_MMU_IO_S                    1102
#define IDC_MMU_CE1_S                   1103
#define IDC_MMU_CE2_S                   1104
#define IDC_MMU_NCE2_S                  1105
#define IDC_MMU_NCE3_S                  1106
#define IDC_STATIC_MISC                 1107
#define IDC_MISC_BS_TXT                 1108
#define IDC_INSTR_TEXT                  1109
#define IDC_INSTR_CODE                  1110
#define IDC_INSTR_COPY                  1111
#define IDC_INSTR_CLEAR                 1112
#define IDC_PROFILE_LASTCYCLES          1113
#define IDC_PROFILE_LASTTIME            1114
#define IDC_BPCODE                      1115
#define IDC_BPRPL                       1116
#define IDC_BPACCESS                    1117
#define IDC_BPREAD                      1118
#define IDC_BPWRITE                     1119
#define IDC_FIND_DATA                   1120
#define IDC_FIND_PREV                   1121
#define IDC_FIND_NEXT                   1122
#define IDC_FIND_ASCII                  1123
#define IDC_ADDR20_24                   1124
#define IDC_ADDR25_27                   1125
#define IDC_ADDR28_29                   1126
#define IDC_ADDR30_34                   1127
#define IDC_RPLVIEW_DATA                1128
#define IDC_MACRO_SLOW                  1129
#define IDC_MACRO_FAST                  1130
#define IDC_MACRO_SLIDER                1131
#define IDC_MACRO_REAL                  1132
#define IDC_MACRO_MANUAL                1133
#define IDC_SOUND_SLIDER                1134
#define IDC_SOUND_DEVICE                1135
#define ID_FILE_NEW                     40001
#define ID_FILE_OPEN                    40002
#define ID_FILE_SAVE                    40003
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_EXIT                    40005
#define ID_VIEW_COPY                    40006
#define ID_VIEW_SETTINGS                40007
#define ID_VIEW_RESET                   40008
#define ID_OBJECT_LOAD                  40009
#define ID_OBJECT_SAVE                  40010
#define ID_ABOUT                        40011
#define ID_HELP_TOPICS                  40012
#define ID_FILE_CLOSE                   40013
#define ID_BACKUP_SAVE                  40014
#define ID_BACKUP_RESTORE               40015
#define ID_BACKUP_DELETE                40016
#define ID_VIEW_SCRIPT                  40017
#define ID_STACK_COPY                   40019
#define ID_STACK_PASTE                  40020
#define ID_TOOL_DISASM                  40021
#define ID_TOOL_DEBUG                   40022
#define ID_TOOL_MACRO_RECORD            40023
#define ID_TOOL_MACRO_PLAY              40024
#define ID_TOOL_MACRO_STOP              40025
#define ID_TOOL_MACRO_SETTINGS          40026
#define ID_DEBUG_RUN                    40027
#define ID_DEBUG_RUNCURSOR              40028
#define ID_DEBUG_STEP                   40029
#define ID_DEBUG_STEPOVER               40030
#define ID_DEBUG_BREAK                  40031
#define ID_DEBUG_STEPOUT                40032
#define ID_DEBUG_CANCEL                 40033
#define ID_BREAKPOINTS_SETBREAK         40034
#define ID_BREAKPOINTS_CODEEDIT         40035
#define ID_BREAKPOINTS_CLEARALL         40036
#define ID_BREAKPOINTS_NOP3             40037
#define ID_BREAKPOINTS_DOCODE           40038
#define ID_BREAKPOINTS_RPL              40039
#define ID_DEBUG_CODE_GOADR             40040
#define ID_DEBUG_CODE_GOPC              40041
#define ID_DEBUG_CODE_SETPCTOSELECT     40042
#define ID_DEBUG_CODE_PREVPCO           40043
#define ID_DEBUG_CODE_NEXTPCO           40044
#define ID_DEBUG_MEM_GOADR              40045
#define ID_DEBUG_MEM_GOPC               40046
#define ID_DEBUG_MEM_GOD0               40047
#define ID_DEBUG_MEM_GOD1               40048
#define ID_DEBUG_MEM_GOSTACK            40049
#define ID_DEBUG_MEM_FNONE              40050
#define ID_DEBUG_MEM_FADDR              40051
#define ID_DEBUG_MEM_FPC                40052
#define ID_DEBUG_MEM_FD0                40053
#define ID_DEBUG_MEM_FD1                40054
#define ID_DEBUG_MEM_FIND               40055
#define ID_DEBUG_MEM_MAP                40056
#define ID_DEBUG_MEM_NCE1               40057
#define ID_DEBUG_MEM_NCE2               40058
#define ID_DEBUG_MEM_CE1                40059
#define ID_DEBUG_MEM_CE2                40060
#define ID_DEBUG_MEM_NCE3               40061
#define ID_DEBUG_MEM_SAVE               40062
#define ID_DEBUG_MEM_LOAD               40063
#define ID_DEBUG_MEM_RPLVIEW            40064
#define ID_DEBUG_STACK_PUSH             40065
#define ID_DEBUG_STACK_POP              40066
#define ID_DEBUG_STACK_MODIFY           40067
#define ID_INTR_STEPOVERINT             40068
#define ID_INFO_LASTINSTRUCTIONS        40069
#define ID_INFO_PROFILE                 40070
#define ID_INFO_WRITEONLYREG            40071
#define ID_FILE_MRU_FILE1               40100

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40072
#define _APS_NEXT_CONTROL_VALUE         1136
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
